# Generated by Django 4.1.1 on 2023-07-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_semester_alter_notes_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='coursecode',
            field=models.CharField(default='MTH212', max_length=20),
            preserve_default=False,
        ),
    ]
