# Generated by Django 4.1.1 on 2023-09-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='downvotes',
            new_name='downvote',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upvotes',
            new_name='upvote',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='pending', max_length=20),
            preserve_default=False,
        ),
    ]
