# Generated by Django 4.1.1 on 2023-09-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_rename_downvotes_post_downvote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='downvote',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upvote',
            new_name='like',
        ),
    ]
