# Generated by Django 4.1.1 on 2023-09-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_rename_downvote_post_dislike_rename_upvote_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='uploaded_on',
        ),
    ]
