# Generated by Django 4.1.1 on 2023-09-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_rename_timestamp_comment_uploaded_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
