# Generated by Django 4.2.2 on 2023-06-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='noteconnect_user',
        ),
    ]
