# Generated by Django 4.1.1 on 2023-07-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
